# Generated by Django 5.0.1 on 2024-01-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_destination_certification_name_destination_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='certification_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='company',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='current_profession',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='education_end_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='education_location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='education_start_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='email',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='establishment',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='language_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='ocr_result',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='skill_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='skill_type',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='title',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='work_description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='work_end_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='work_location',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='work_start_date',
        ),
    ]
