# Generated by Django 5.0.1 on 2024-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_remove_document_degree_document_education_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='urls',
            field=models.CharField(default='Not available', max_length=255, null=True),
        ),
    ]
