# Generated by Django 5.0.1 on 2024-01-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_document_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='establishment',
        ),
    ]
