# Generated by Django 5.0.1 on 2024-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_remove_document_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
